### ISSUE TITLE
add new model: cash flow statement

### ISSUE THREAD

**Issue by bmayer99** [fivetran/dbt_netsuite#22]
adding the cash flow statement to the models would allow the NetSuite package to deliver complete financial statements and unleash some interesting modeling capabilities around cash flow projections.

**Comment by fivetran-kristin** [comment]
Cross -posting here: 

Hi Benoit! Thanks for the request.  

Adding the cash flow statement would definitely compliment our existing offering.  I've talked to two customers about adding this functionality, and it seems like the logic may be quite tricky depending on how your company customizes the adjustments made to the cash flow statement.  Would you be willing to set up a quick call so that we can chat through how you approach building the cash flow statement?  

Feel free to book some time [here](5tran.co/office-hours).

Best,

Kristin
