### ISSUE TITLE
BUG - Balance sheet limited to 100 results

### ISSUE THREAD

**Issue by bmayer99** [fivetran/dbt_netsuite#29]
**Are you a current Fivetran customer?** 
Benoit Mayer - Stedi

**Describe the bug**
The balance sheet model does not produce full results
I think the line below should be removed https://github.com/fivetran/dbt_netsuite/blob/13fddb854c2e4644c262b150622c831ebb216268/models/netsuite__balance_sheet.sql#L178

**Package Version**
`0.3.1`

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
@bmayer99 you are indeed correct that the line you mentioned should be removed. That limit was a holdover from our testing of the release of the package and it has since been removed. I have pushed the change to `master` and cut a new `v0.3.2` release of the netsuite package. I also ensured there are no other limits throughout the package. 

This release should be live on the dbt hub most likely tomorrow morning. Thanks again for catching this issue and calling it out to our team.
