### ISSUE TITLE
[Bug] Income Statement in Netsuite2 Snowflake from Fivetran dbt package only shows handful of transactions (whereas transaction_details has all)

### ISSUE THREAD

**Issue by wwilliamsnuwest** [fivetran/dbt_netsuite#50]
Our Fivetran Netsuite2 dbt package-created table netsuite2__income_statement in Snowflake only shows handful of transactions (whereas netsuite2__transaction_details has all). For example, if I run:
`SELECT *
FROM dbt_db.dbt_prod_netsuite.netsuite2__income_statement`

I only see these 7 transactions, whereas we should have 10s or 100s of thousands to sum to a much higher dollar amount. It's possible that there's custom dev in Netsuite, but I would assume the core functionality should work for income statement since it seems to work for transaction_details. One other note is that we do everything in USD, so perhaps there's some issue with exchange rates, but again, that's just a wild guess (and anecdotally I dug through some of the exchange rate tables in the dbt-shown lineage and they appeared to have populated exchange rates of 1 for USD.)

![image](https://user-images.githubusercontent.com/100794323/194393822-65c0ff8f-fbeb-4cc9-99ec-b90dd274bcb0.png)

**Comment by wwilliamsnuwest** [comment]
Showing the ~500 K row count for transaction_details: 
![image](https://user-images.githubusercontent.com/100794323/194395003-d9326433-6496-47b5-90ae-9f02c8e329cc.png)

And the 7 row count for income_statement:
![image](https://user-images.githubusercontent.com/100794323/194395333-5ca69600-8578-4f67-90a5-3ad03b4f7f45.png)

I haven't looked at balance_sheet, so I can't say anything about whether or not that one's correct), but it has 296 rows, which feels small, but again, I'm not sure what that table is supposed to look like:

![image](https://user-images.githubusercontent.com/100794323/194395163-f32d83c8-4bad-4367-9ab0-9491ba881da0.png)

**Comment by fivetran-joemarkiewicz** [comment]
HI @wwilliamsnuwest thanks for opening this issue and sorry to see you are experiencing issues.

I agree with you that I would imagine the income statement model would have more rows. However, I am curious of a few things:
- Have you tried to rerun the dbt package and view the output? Just want to confirm there is not something that errored out on an initial run and just needs to be re-kicked off.
- In your base transactions table, are you seeing the `accounting_period_id` field populated? The Income and Balance Sheet models are generated using this field to properly designate the respective periods of the transactions. I would assume `null` records for these fields could result in this issue 🤔 

Let me know what you find!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @wwilliamsnuwest I just wanted to check back in if you were able to find anything from your investigation?

I know the other issues you created tend to go back to the duplicate entry from the source data. Do you think the same issue could be arising here? Happy to help dig in more if needed 😄

**Comment by wwilliamsnuwest** [comment]
I haven't, and haven't been looking recently since I've been busy with other stuff. Thanks for asking though, so far as I know it's still an outstanding problem, but I haven't checked in the past 4 weeks or so to see if anything's changed on the dbt side.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fivetran-joemarkiewicz** [comment]
Hey @wwilliamsnuwest I think I may have found the culprit to this issue! I am testing on our own data and an odd discrepancy when comparing Netsuite to Netsuite2. It seemed that our Netsuite2 income statement was only outputting non_posting transactions in the final model. 🤔 

It turns out we have a problematic filter in the `int_netsuite2__tran_lines_w_accounting_period` model that is filtering on the wrong records. You can see [here](https://github.com/fivetran/dbt_netsuite/blob/c1fe30ec1b1164679e74bfbf03ec605e00ebc400/models/netsuite2/intermediate/int_netsuite2__tran_lines_w_accounting_period.sql#L26) that we are filtering out posting accounts. Whereas we should be filtering to **only include posting accounts** as opposed to the inverse.

I found it interesting that this was not an issue within Netsuite and went to look at the mirror model to see how we were performing this filter. It seems Netsuite just named the original field very confusingly `non_posting_account` and we filtered out the `yes` records. As `yes` for non_posting_account means that it is not a posting account, and `no` means it is. 🤕 You can see the Netsuite filter [here](https://github.com/fivetran/dbt_netsuite/blob/c1fe30ec1b1164679e74bfbf03ec605e00ebc400/models/netsuite/intermediate/int_netsuite__transaction_lines_w_accounting_period.sql#L26).

As such, I believe if we change the Netsuite2 model to perform the following adjustment to the filter, then we should address this problem.
```sql
-- models/netsuite2/intermediate/int_netsuite2__tran_lines_w_accounting_period

  where lower(transactions.transaction_type) != 'revenue arrangement'
    and transaction_lines.is_posting -- previously "and not transaction_lines.is_posting"
```

**Comment by wwilliamsnuwest** [comment]
Sounds like great news Joe! Please let me know whenever Fivetran releases this change as an update to the dbt model & I will run 'dbt deps' to get the latest in my dev code (my prod code will automatically bring it in.)

Thanks!!!
Ward
________________________________

**Comment by fivetran-joemarkiewicz** [comment]
Hi @wwilliamsnuwest I apologize for the late response. On 12/5 we were able to push the update to the `v0.6.3` release of the package.

As such, this issue should be resolved and I will close out the issue. Please feel free to re-open the issue if you see the issue persist.
